# Generated by Django 6.0.2 on 2026-02-19 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custSupApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
