# Generated by Django 6.0.2 on 2026-03-05 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custSupApp', '0004_delete_supportstaff_supportticket_assigned_to_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='supportticket',
            name='category',
            field=models.CharField(choices=[('authentication', 'Authentication'), ('billing', 'Billing'), ('technical', 'Technical'), ('general', 'General')], default='general', max_length=100),
        ),
        migrations.AddField(
            model_name='supportticket',
            name='context',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='supportticket',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='supportticket',
            name='priority',
            field=models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High')], default='normal', max_length=20),
        ),
    ]
