# Generated by Django 6.0.2 on 2026-03-05 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custSupApp', '0005_supportticket_category_supportticket_context_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supportticket',
            name='category',
            field=models.CharField(choices=[('authentication', 'Authentication'), ('billing', 'Billing'), ('technical', 'Technical'), ('general', 'General')], db_index=True, default='general', max_length=100),
        ),
        migrations.AlterField(
            model_name='supportticket',
            name='priority',
            field=models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High')], db_index=True, default='normal', max_length=20),
        ),
    ]
