# Generated by Django 6.0.2 on 2026-04-02 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custSupApp', '0012_ticketfeedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedpdf',
            name='file_url',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='uploadedpdf',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='pdfs/'),
        ),
    ]
