# Generated by Django 6.0.2 on 2026-04-03 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custSupApp', '0013_uploadedpdf_file_url_alter_uploadedpdf_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedpdf',
            name='is_indexed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='uploadedpdf',
            name='last_processed_page',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='uploadedpdf',
            name='status',
            field=models.CharField(db_index=True, default='queued', max_length=20),
        ),
        migrations.AddField(
            model_name='uploadedpdf',
            name='total_pages',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
