# Generated by Django 6.0.2 on 2026-04-14 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custSupApp', '0014_uploadedpdf_is_indexed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supportticket',
            name='resolution_note',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='uploadedpdf',
            name='file_url',
            field=models.TextField(blank=True, default=''),
        ),
    ]
