# Generated by Django 6.0.2 on 2026-05-01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custSupApp', '0015_alter_supportticket_resolution_note_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='ticket',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='chat_messages',
                to='custSupApp.supportticket',
            ),
        ),
    ]