# Generated by Django 6.0.2 on 2026-05-01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custSupApp', '0016_chatmessage_ticket'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedpdf',
            name='file_type',
            field=models.CharField(
                choices=[
                    ('pdf', 'PDF'),
                    ('excel', 'Excel'),
                    ('csv', 'CSV'),
                    ('word', 'Word'),
                ],
                default='pdf',
                max_length=20,
                db_index=True
            ),
        ),
    ]