# Generated by Django 6.0.2 on 2026-05-01 12:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custSupApp', '0017_uploadeddocument_file_type'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UploadedPDF',
            new_name='UploadedDocument',
        ),
    ]
