# Generated by Django 6.0.2 on 2026-05-01 12:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custSupApp', '0018_uploadeddocument_delete_uploadedpdf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadeddocument',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='documents/'),
        ),
        migrations.AlterField(
            model_name='uploadeddocument',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='custSupApp.organization'),
        ),
        migrations.AlterModelTable(
            name='uploadeddocument',
            table='custSupApp_uploadedpdf',
        ),
    ]
