sonar.sources=backend,frontend
sonar.tests=backend,frontend
sonar.test.inclusions=backend/**/tests.py,backend/**/tests/**/*.py,frontend/**/__tests__/**/*.test.ts,frontend/**/__tests__/**/*.test.tsx
sonar.exclusions=backend/**/migrations/**,backend/env/**,backend/media/**,frontend/coverage/**,frontend/.next/**,node_modules/**
sonar.python.coverage.reportPaths=backend/coverage.xml
sonar.javascript.lcov.reportPaths=frontend/coverage/lcov.info
